#!/bin/sh

case "$1" in
    start)
        echo "Loading the realtek module..."
        modprobe rtw88_8821cu
        echo "Switching the mode of the USB dongle..."
        usb_modeswitch -v 0bda -p 1a2b -V 0bda -P 1a2b -M "5553424312345678000000000000061b000000020000000000000000000000"
        ;;
    stop)
        # modprobe -r snd_usb_audio
        ;;
    *) exit 1 ;;
esac